drop table if exists input.building_permits;

create table input.building_permits (
	id integer not null, 
	permit_number text not null, 
	permit_type text not null, 
	issue_date date, 
	estimated_cost text, 
	amount_waived text not null, 
	amount_paid text not null, 
	total_fee text not null, 
	street_number integer not null, 
	street_direction text not null, 
	street_name text not null, 
	suffix text, 
	work_description text, 
	pin1 text, 
	pin2 text, 
	pin3 text, 
	pin4 text, 
	pin5 text, 
	pin6 text, 
	pin7 text, 
	pin8 text, 
	pin9 text, 
	pin10 text, 
	contractor_1_type text, 
	contractor_1_name text, 
	contractor_1_address text, 
	contractor_1_city text, 
	contractor_1_state text, 
	contractor_1_zipcode text, 
	contractor_1_phone text, 
	contractor_2_type text, 
	contractor_2_name text, 
	contractor_2_address text, 
	contractor_2_city text, 
	contractor_2_state text, 
	contractor_2_zipcode text, 
	contractor_2_phone text, 
	contractor_3_type text, 
	contractor_3_name text, 
	contractor_3_address text, 
	contractor_3_city text, 
	contractor_3_state text, 
	contractor_3_zipcode text, 
	contractor_3_phone text, 
	contractor_4_type text, 
	contractor_4_name text, 
	contractor_4_address text, 
	contractor_4_city text, 
	contractor_4_state text, 
	contractor_4_zipcode text, 
	contractor_4_phone text, 
	contractor_5_type text, 
	contractor_5_name text, 
	contractor_5_address text, 
	contractor_5_city text, 
	contractor_5_state text, 
	contractor_5_zipcode text, 
	contractor_5_phone text, 
	contractor_6_type text, 
	contractor_6_name text, 
	contractor_6_address text, 
	contractor_6_city text, 
	contractor_6_state text, 
	contractor_6_zipcode text, 
	contractor_6_phone text, 
	contractor_7_type text, 
	contractor_7_name text, 
	contractor_7_address text, 
	contractor_7_city text, 
	contractor_7_state text, 
	contractor_7_zipcode text, 
	contractor_7_phone text, 
	contractor_8_type text, 
	contractor_8_name text, 
	contractor_8_address text, 
	contractor_8_city text, 
	contractor_8_state text, 
	contractor_8_zipcode text, 
	contractor_8_phone text, 
	contractor_9_type text, 
	contractor_9_name text, 
	contractor_9_address text, 
	contractor_9_city text, 
	contractor_9_state text, 
	contractor_9_zipcode text, 
	contractor_9_phone text, 
	contractor_10_type text, 
	contractor_10_name text, 
	contractor_10_address text, 
	contractor_10_city text, 
	contractor_10_state text, 
	contractor_10_zipcode text, 
	contractor_10_phone text, 
	contractor_11_type text, 
	contractor_11_name text, 
	contractor_11_address text, 
	contractor_11_city text, 
	contractor_11_state text, 
	contractor_11_zipcode text, 
	contractor_11_phone text, 
	contractor_12_type text, 
	contractor_12_name text, 
	contractor_12_address text, 
	contractor_12_city text, 
	contractor_12_state text, 
	contractor_12_zipcode text, 
	contractor_12_phone text, 
	contractor_13_type text, 
	contractor_13_name text, 
	contractor_13_address text, 
	contractor_13_city text, 
	contractor_13_state text, 
	contractor_13_zipcode text, 
	contractor_13_phone text, 
	contractor_14_type text, 
	contractor_14_name text, 
	contractor_14_address text, 
	contractor_14_city text, 
	contractor_14_state text, 
	contractor_14_zipcode text, 
	contractor_14_phone text, 
	contractor_15_type text, 
	contractor_15_name text, 
	contractor_15_address text, 
	contractor_15_city text, 
	contractor_15_state text, 
	contractor_15_zipcode integer, 
	contractor_15_phone text, 
	latitude float, 
	longitude float, 
	location varchar(40)
);

\copy input.building_permits from 'data/building_permits.csv' with csv header;
